# Generated by Django 5.2.9 on 2025-12-10 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA256 hash of the refresh token', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was created')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this token expires')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this token was last used for refresh', null=True)),
                ('revoked', models.BooleanField(db_index=True, default=False, help_text='Whether this token has been revoked')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this token was revoked', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where token was created', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from token creation request')),
                ('device', models.ForeignKey(blank=True, help_text='Device this token is associated with (if tracked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_tokens', to='core.device')),
                ('replaced_by', models.ForeignKey(blank=True, help_text='New token that replaced this one (for rotation tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_token', to='accounts.refreshtoken')),
                ('user', models.ForeignKey(help_text='User who owns this refresh token', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_re_user_id_a0960a_idx'), models.Index(fields=['expires_at'], name='accounts_re_expires_d12447_idx'), models.Index(fields=['revoked', 'expires_at'], name='accounts_re_revoked_167ef9_idx')],
            },
        ),
    ]
