# Generated by Django 5.2.9 on 2025-12-23 20:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique identifier for this canonical record.', primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, help_text='Stable, opaque identifier for external use (APIs, exports). This ID should remain stable across versions of the same logical entity.', max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this record. Increments when evaluation logic updates the entity. Multiple versions may exist for the same logical entity.')),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this version became valid (inclusive).')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='When this version was superseded (exclusive). NULL means this is the current valid version.', null=True)),
                ('structural_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Long-term stability confidence (0.0 to 1.0). Represents how well-established this entity is. Higher = more evidence over time.', max_digits=5)),
                ('freshness_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Recency-based confidence (0.0 to 1.0). Decays over time without reinforcing evidence. Higher = recently confirmed.', max_digits=5)),
                ('ruleset_version', models.CharField(default='1.0', help_text='Version identifier of the evaluation rules used to derive this record. Enables recomputation when rules change.', max_length=50)),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='Array of ContributionEvent IDs that support this canonical record. Used for provenance, audit, and recomputation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this canonical record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this canonical record was last updated by evaluation logic.')),
                ('name', models.CharField(help_text="Full name of the route. Examples: 'Downtown Circulator', 'Airport Express'", max_length=255)),
                ('short_name', models.CharField(blank=True, default='', help_text="Short identifier for the route. Examples: '42', 'A', 'Red', 'M1'", max_length=50)),
                ('route_type', models.CharField(choices=[('bus', 'Bus'), ('tram', 'Tram/Light Rail'), ('metro', 'Metro/Subway'), ('rail', 'Rail'), ('ferry', 'Ferry'), ('cable', 'Cable Car'), ('gondola', 'Gondola'), ('funicular', 'Funicular'), ('trolleybus', 'Trolleybus'), ('monorail', 'Monorail'), ('other', 'Other')], default='bus', help_text='Type of transit service.', max_length=20)),
                ('operator', models.CharField(blank=True, default='', help_text='Name of the transit operator/agency. May be derived from contributions or left unknown.', max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Flexible JSON for additional route attributes. Examples: color, text_color, url, description. Structure is flexible and domain-specific.')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='transit_rou_name_9dd39d_idx'), models.Index(fields=['short_name'], name='transit_rou_short_n_2a4879_idx'), models.Index(fields=['route_type'], name='transit_rou_route_t_2c34ff_idx'), models.Index(fields=['valid_from', 'valid_until'], name='transit_rou_valid_f_232385_idx'), models.Index(fields=['structural_confidence'], name='transit_rou_structu_0cfd5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique identifier for this canonical record.', primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, help_text='Stable, opaque identifier for external use (APIs, exports). This ID should remain stable across versions of the same logical entity.', max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this record. Increments when evaluation logic updates the entity. Multiple versions may exist for the same logical entity.')),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this version became valid (inclusive).')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='When this version was superseded (exclusive). NULL means this is the current valid version.', null=True)),
                ('structural_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Long-term stability confidence (0.0 to 1.0). Represents how well-established this entity is. Higher = more evidence over time.', max_digits=5)),
                ('freshness_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Recency-based confidence (0.0 to 1.0). Decays over time without reinforcing evidence. Higher = recently confirmed.', max_digits=5)),
                ('ruleset_version', models.CharField(default='1.0', help_text='Version identifier of the evaluation rules used to derive this record. Enables recomputation when rules change.', max_length=50)),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='Array of ContributionEvent IDs that support this canonical record. Used for provenance, audit, and recomputation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this canonical record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this canonical record was last updated by evaluation logic.')),
                ('name', models.CharField(help_text="Descriptive name for this variant. Examples: '42 to Downtown', '42 to Airport'", max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('clockwise', 'Clockwise'), ('counterclockwise', 'Counter-clockwise'), ('north', 'Northbound'), ('south', 'Southbound'), ('east', 'Eastbound'), ('west', 'Westbound'), ('one_way', 'One-way (loop)'), ('unknown', 'Unknown')], default='unknown', help_text='Direction identifier for this variant.', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, help_text='Geographic path of the route variant (WGS84). May be derived from aggregated route_traversal GPS traces.', null=True, srid=4326)),
                ('headsign', models.CharField(blank=True, default='', help_text="Destination sign text displayed on vehicles. Examples: 'Downtown', 'Airport Terminal'", max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Flexible JSON for additional variant attributes. Examples: service_type, exceptions, notes. Structure is flexible and domain-specific.')),
                ('route', models.ForeignKey(help_text='Parent route this variant belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='transit.route')),
            ],
            options={
                'verbose_name': 'Route Variant',
                'verbose_name_plural': 'Route Variants',
                'ordering': ['route', 'direction', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique identifier for this canonical record.', primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, help_text='Stable, opaque identifier for external use (APIs, exports). This ID should remain stable across versions of the same logical entity.', max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this record. Increments when evaluation logic updates the entity. Multiple versions may exist for the same logical entity.')),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this version became valid (inclusive).')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='When this version was superseded (exclusive). NULL means this is the current valid version.', null=True)),
                ('structural_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Long-term stability confidence (0.0 to 1.0). Represents how well-established this entity is. Higher = more evidence over time.', max_digits=5)),
                ('freshness_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Recency-based confidence (0.0 to 1.0). Decays over time without reinforcing evidence. Higher = recently confirmed.', max_digits=5)),
                ('ruleset_version', models.CharField(default='1.0', help_text='Version identifier of the evaluation rules used to derive this record. Enables recomputation when rules change.', max_length=50)),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='Array of ContributionEvent IDs that support this canonical record. Used for provenance, audit, and recomputation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this canonical record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this canonical record was last updated by evaluation logic.')),
                ('name', models.CharField(help_text='Primary name of the stop. May be derived from highest-confidence stop_name contributions.', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic location of the stop (WGS84). May be derived from aggregated stop_location contributions.', srid=4326)),
                ('alternate_names', models.JSONField(blank=True, default=list, help_text="Array of alternate names observed for this stop. Format: [{'name': 'Main St', 'confidence': 0.7}, ...] Populated by evaluation logic from stop_name contributions.")),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Flexible JSON for additional stop attributes. Examples: wheelchair_accessible, shelter, bench, lighting. Structure is flexible and domain-specific.')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='transit_sto_name_5407a0_idx'), models.Index(fields=['valid_from', 'valid_until'], name='transit_sto_valid_f_6a5604_idx'), models.Index(fields=['structural_confidence'], name='transit_sto_structu_70fa9a_idx'), models.Index(fields=['freshness_confidence'], name='transit_sto_freshne_bfbd0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObservedServiceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique identifier for this canonical record.', primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, help_text='Stable, opaque identifier for external use (APIs, exports). This ID should remain stable across versions of the same logical entity.', max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this record. Increments when evaluation logic updates the entity. Multiple versions may exist for the same logical entity.')),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this version became valid (inclusive).')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='When this version was superseded (exclusive). NULL means this is the current valid version.', null=True)),
                ('structural_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Long-term stability confidence (0.0 to 1.0). Represents how well-established this entity is. Higher = more evidence over time.', max_digits=5)),
                ('freshness_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Recency-based confidence (0.0 to 1.0). Decays over time without reinforcing evidence. Higher = recently confirmed.', max_digits=5)),
                ('ruleset_version', models.CharField(default='1.0', help_text='Version identifier of the evaluation rules used to derive this record. Enables recomputation when rules change.', max_length=50)),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='Array of ContributionEvent IDs that support this canonical record. Used for provenance, audit, and recomputation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this canonical record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this canonical record was last updated by evaluation logic.')),
                ('day_of_week', models.JSONField(default=list, help_text="Array of day names this window applies to. Values: monday, tuesday, wednesday, thursday, friday, saturday, sunday. Example: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']")),
                ('first_observed_time', models.TimeField(blank=True, help_text='Earliest service time observed for this window. Example: 06:30 (meaning service starts around 6:30 AM).', null=True)),
                ('last_observed_time', models.TimeField(blank=True, help_text='Latest service time observed for this window. Example: 22:00 (meaning service runs until around 10:00 PM).', null=True)),
                ('typical_frequency_minutes', models.PositiveIntegerField(blank=True, help_text='Approximate frequency in minutes if known. Example: 15 means buses approximately every 15 minutes. NULL if frequency is unknown or irregular.', null=True)),
                ('observation_count', models.PositiveIntegerField(default=0, help_text='Number of service_time observations supporting this window. Higher counts generally mean higher confidence.')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Flexible JSON for additional service window attributes. Examples: peak_hours, notes, seasonal_variations. Structure is flexible and domain-specific.')),
                ('route_variant', models.ForeignKey(help_text='The route variant this service window applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='service_windows', to='transit.routevariant')),
                ('stop', models.ForeignKey(blank=True, help_text='Optional: specific stop this window applies to. NULL means this is a route-level window.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_windows', to='transit.stop')),
            ],
            options={
                'verbose_name': 'Observed Service Window',
                'verbose_name_plural': 'Observed Service Windows',
                'ordering': ['route_variant', 'day_of_week', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StopRouteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique identifier for this canonical record.', primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, help_text='Stable, opaque identifier for external use (APIs, exports). This ID should remain stable across versions of the same logical entity.', max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this record. Increments when evaluation logic updates the entity. Multiple versions may exist for the same logical entity.')),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this version became valid (inclusive).')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='When this version was superseded (exclusive). NULL means this is the current valid version.', null=True)),
                ('structural_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Long-term stability confidence (0.0 to 1.0). Represents how well-established this entity is. Higher = more evidence over time.', max_digits=5)),
                ('freshness_confidence', models.DecimalField(decimal_places=4, default=0.0, help_text='Recency-based confidence (0.0 to 1.0). Decays over time without reinforcing evidence. Higher = recently confirmed.', max_digits=5)),
                ('ruleset_version', models.CharField(default='1.0', help_text='Version identifier of the evaluation rules used to derive this record. Enables recomputation when rules change.', max_length=50)),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='Array of ContributionEvent IDs that support this canonical record. Used for provenance, audit, and recomputation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this canonical record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this canonical record was last updated by evaluation logic.')),
                ('sequence', models.PositiveIntegerField(help_text="Position of this stop in the route variant's sequence. 1 = first stop, 2 = second stop, etc. Used to order stops along the route.")),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Flexible JSON for additional link attributes. Examples: timepoint (bool), pickup_type, drop_off_type. Structure is flexible and domain-specific.')),
                ('route_variant', models.ForeignKey(help_text='The route variant in this association.', on_delete=django.db.models.deletion.PROTECT, related_name='stop_links', to='transit.routevariant')),
                ('stop', models.ForeignKey(help_text='The stop in this association.', on_delete=django.db.models.deletion.PROTECT, related_name='route_links', to='transit.stop')),
            ],
            options={
                'verbose_name': 'Stop Route Link',
                'verbose_name_plural': 'Stop Route Links',
                'ordering': ['route_variant', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='routevariant',
            index=models.Index(fields=['route', 'direction'], name='transit_rou_route_i_2a92d3_idx'),
        ),
        migrations.AddIndex(
            model_name='routevariant',
            index=models.Index(fields=['valid_from', 'valid_until'], name='transit_rou_valid_f_9b8251_idx'),
        ),
        migrations.AddIndex(
            model_name='routevariant',
            index=models.Index(fields=['structural_confidence'], name='transit_rou_structu_2f12ed_idx'),
        ),
        migrations.AddIndex(
            model_name='observedservicewindow',
            index=models.Index(fields=['route_variant', 'stop'], name='transit_obs_route_v_da7e37_idx'),
        ),
        migrations.AddIndex(
            model_name='observedservicewindow',
            index=models.Index(fields=['valid_from', 'valid_until'], name='transit_obs_valid_f_6a0d80_idx'),
        ),
        migrations.AddIndex(
            model_name='observedservicewindow',
            index=models.Index(fields=['structural_confidence'], name='transit_obs_structu_ee43b8_idx'),
        ),
        migrations.AddIndex(
            model_name='observedservicewindow',
            index=models.Index(fields=['observation_count'], name='transit_obs_observa_31f6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='stoproutelink',
            index=models.Index(fields=['stop', 'route_variant'], name='transit_sto_stop_id_584790_idx'),
        ),
        migrations.AddIndex(
            model_name='stoproutelink',
            index=models.Index(fields=['route_variant', 'sequence'], name='transit_sto_route_v_1e668b_idx'),
        ),
        migrations.AddIndex(
            model_name='stoproutelink',
            index=models.Index(fields=['valid_from', 'valid_until'], name='transit_sto_valid_f_2d3357_idx'),
        ),
        migrations.AddIndex(
            model_name='stoproutelink',
            index=models.Index(fields=['structural_confidence'], name='transit_sto_structu_574974_idx'),
        ),
        migrations.AddConstraint(
            model_name='stoproutelink',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_until__isnull', True)), fields=('route_variant', 'sequence', 'valid_until'), name='unique_sequence_per_variant_version'),
        ),
    ]
