# Generated by Django 5.2.9 on 2025-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='belief_state',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('active_low', 'Active (Low Confidence)'), ('active_high', 'Active (High Confidence)'), ('contested', 'Contested'), ('dormant', 'Dormant')], default='proposed', help_text='Human-legible projection of Stop confidence (Sprint-4D). Derived from structural_confidence, freshness_confidence, and presence of negative evidence. Not a workflow state.', max_length=20),
        ),
    ]
