# Generated by Django 5.2.9 on 2026-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_add_belief_state_to_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='belief_state',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('active_low', 'Active (Low Confidence)'), ('active_high', 'Active (High Confidence)'), ('contested', 'Contested'), ('dormant', 'Dormant')], default='proposed', help_text='Human-legible projection of Route confidence (Phase-2 Sprint-6). Derived from structural_confidence, freshness_confidence, and presence of negative evidence. Not a workflow state.', max_length=20),
        ),
    ]
