# Generated by Django 5.2.9 on 2026-02-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_add_belief_state_to_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='belief_state',
        ),
    ]
