# Generated by Django 5.2.9 on 2025-12-10 17:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this badge', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Unique name of the badge (e.g., 'first_contribution')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable display name (e.g., 'First Contribution')", max_length=100)),
                ('description', models.TextField(help_text='Description of what this badge represents')),
                ('icon_url', models.URLField(blank=True, help_text='URL to badge icon image', max_length=500)),
                ('tier', models.CharField(blank=True, help_text='Badge tier/rarity (bronze, silver, gold, etc.)', max_length=20)),
                ('points', models.IntegerField(default=0, help_text='Points awarded for earning this badge')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this badge is currently active and earnable')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this badge was created')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this developer', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Developer or organization name', max_length=200)),
                ('contact_email', models.EmailField(help_text='Contact email for this developer', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Developer website or documentation URL', max_length=500)),
                ('verified', models.BooleanField(default=False, help_text='Whether this developer has been verified by administrators')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', help_text='API access tier', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this developer')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this developer account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this developer account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this developer account was last updated')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user (UUID v4)', primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, db_index=True, help_text='Public display name for attributions and leaderboards', max_length=100)),
                ('email_verified', models.BooleanField(db_index=True, default=False, help_text='Whether the user has verified their email address')),
                ('privacy_consent_version', models.CharField(blank=True, help_text="Version of privacy policy consented to (e.g., '1.0', '2.1')", max_length=20, null=True)),
                ('privacy_consent_ts', models.DateTimeField(blank=True, help_text='Timestamp when user consented to privacy policy', null=True)),
                ('public_profile', models.BooleanField(default=True, help_text="Whether the user's profile is publicly visible")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this contribution', primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, help_text='Type of contribution (route_update, stop_edit, etc.)', max_length=50)),
                ('payload', models.JSONField(help_text='Contribution data (structure varies by type)')),
                ('external_user_id', models.CharField(blank=True, help_text='External user identifier (from partner systems)', max_length=200)),
                ('source_type', models.CharField(choices=[('ui', 'Web/Mobile UI'), ('api', 'Developer API'), ('bulk', 'Bulk Import'), ('external', 'External Integration')], db_index=True, default='ui', help_text='Source of this contribution', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client-provided key for idempotent submission', max_length=200)),
                ('payload_fingerprint', models.CharField(blank=True, db_index=True, help_text='SHA256 hash of payload for duplicate detection', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('flagged', 'Flagged')], db_index=True, default='pending', help_text='Current status in moderation workflow', max_length=20)),
                ('points_awarded', models.IntegerField(default=0, help_text='Points awarded to submitter for this contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this contribution was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this contribution was last updated')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Authenticated user who submitted this contribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by_developer', models.ForeignKey(blank=True, help_text='Developer/API client that submitted this contribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='core.developer')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(help_text='Auto-incrementing ID for audit log entries', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this action occurred')),
                ('action', models.CharField(db_index=True, help_text="Type of action (e.g., 'user.login', 'contribution.create')", max_length=100)),
                ('object_type', models.CharField(blank=True, help_text="Type of object affected (e.g., 'Contribution', 'User')", max_length=50)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object affected', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Additional details about this action')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('actor_developer', models.ForeignKey(blank=True, help_text='Developer/API client that performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.developer')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this device', primary_key=True, serialize=False)),
                ('sdk_version', models.CharField(blank=True, help_text="SDK or app version (e.g., '1.2.3')", max_length=50)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('other', 'Other')], default='other', help_text='Device platform', max_length=20)),
                ('device_info', models.CharField(blank=True, help_text='Device information (OS version, model, etc.)', max_length=200)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True, help_text='When this device last accessed the platform')),
                ('opt_in_flags', models.JSONField(blank=True, default=dict, help_text='Opt-in preferences (analytics, notifications, etc.)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional device metadata')),
                ('push_token', models.CharField(blank=True, help_text='Push notification token (FCM/APNS)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this device was first registered')),
                ('user', models.ForeignKey(blank=True, help_text='User this device is associated with (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(help_text='Internal ID for this leaderboard entry', primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, help_text='Period identifier (all-time, monthly-YYYY-MM, weekly-YYYY-WW)', max_length=50)),
                ('rank', models.IntegerField(help_text='Rank within this period (1 = first place)')),
                ('points', models.IntegerField(default=0, help_text='Points earned in this period')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metrics (contributions, badges, etc.)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this leaderboard entry was last updated')),
                ('user', models.ForeignKey(help_text='User being ranked', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['period', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ModerationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag for Review'), ('publish', 'Publish')], help_text='Moderation action taken', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Text explanation for the moderation decision')),
                ('previous_status', models.CharField(blank=True, help_text='Status before this moderation action', max_length=20)),
                ('new_status', models.CharField(blank=True, help_text='Status after this moderation action', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (automated checks, confidence scores, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this moderation action was taken')),
                ('contribution', models.ForeignKey(help_text='Contribution being moderated', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_log', to='core.contribution')),
                ('moderator', models.ForeignKey(blank=True, help_text='User who performed this moderation action (null for automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Entry',
                'verbose_name_plural': 'Moderation Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OSMCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_user_id', models.BigIntegerField(help_text='OpenStreetMap user ID', unique=True)),
                ('osm_username', models.CharField(help_text='OpenStreetMap username', max_length=255)),
                ('access_token_enc', models.CharField(help_text='OAuth access token (TODO: ENCRYPT THIS FIELD)', max_length=500)),
                ('refresh_token_enc', models.CharField(blank=True, help_text='OAuth refresh token (TODO: ENCRYPT THIS FIELD)', max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='When the OSM account was first linked')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the OSM credentials were last used', null=True)),
                ('user', models.OneToOneField(help_text='User who linked this OSM account', on_delete=django.db.models.deletion.CASCADE, related_name='osm_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OSM Credential',
                'verbose_name_plural': 'OSM Credentials',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text="User's self-description (max 500 characters)", max_length=500)),
                ('avatar_url', models.URLField(blank=True, help_text="URL to user's avatar image", max_length=500)),
                ('location_text', models.CharField(blank=True, help_text='User-entered location text (not geocoded)', max_length=200)),
                ('profile_settings', models.JSONField(blank=True, default=dict, help_text='Flexible settings storage (UI prefs, notifications, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated')),
                ('user', models.OneToOneField(help_text='User this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, help_text='When the user earned this badge')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional metadata about how this badge was earned')),
                ('badge', models.ForeignKey(help_text='Badge that was earned', on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='core.badge')),
                ('user', models.ForeignKey(help_text='User who earned this badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions_total', models.BigIntegerField(default=0, help_text='Total number of contributions submitted by this user')),
                ('edits_published', models.BigIntegerField(default=0, help_text='Number of contributions that have been published')),
                ('reviews_approved', models.BigIntegerField(default=0, help_text='Number of contributions approved by moderators')),
                ('reputation_score', models.FloatField(db_index=True, default=0.0, help_text='Computed reputation score (indexed for leaderboard queries)')),
                ('leaderboard_rank_cache', models.IntegerField(blank=True, help_text='Cached global leaderboard rank (updated periodically)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When these stats were last updated')),
                ('user', models.OneToOneField(help_text='User these stats belong to', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['display_name'], name='core_user_display_10f7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified'], name='core_user_email_v_2de8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['type', 'status'], name='core_contri_type_eafa60_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['submitted_by', '-created_at'], name='core_contri_submitt_dcfd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['status', '-created_at'], name='core_contri_status_616dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['idempotency_key'], name='core_contri_idempot_cc53bb_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['payload_fingerprint'], name='core_contri_payload_e2e858_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user', '-created_at'], name='core_auditl_actor_u_8dc22f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', '-last_seen'], name='core_device_user_id_c55cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['platform', '-last_seen'], name='core_device_platfor_078e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['period', 'rank'], name='core_leader_period_6aeb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['period', '-points'], name='core_leader_period_4bb3f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('period', 'user'), name='unique_period_user'),
        ),
        migrations.AddIndex(
            model_name='moderationentry',
            index=models.Index(fields=['contribution', '-created_at'], name='core_modera_contrib_139bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationentry',
            index=models.Index(fields=['moderator', '-created_at'], name='core_modera_moderat_9f02cf_idx'),
        ),
        migrations.AddIndex(
            model_name='osmcredential',
            index=models.Index(fields=['osm_user_id'], name='core_osmcre_osm_use_f05971_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_badge'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['-reputation_score'], name='core_userst_reputat_2c3944_idx'),
        ),
    ]
