# Generated by Django 5.2.9 on 2025-12-23 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this immutable record was created (server time).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Server-generated unique identifier for this contribution event.', primary_key=True, serialize=False)),
                ('client_generated_id', models.UUIDField(db_index=True, help_text='Client-generated UUID for idempotency. Duplicate submissions with the same ID are ignored.', unique=True)),
                ('device_id', models.UUIDField(blank=True, db_index=True, help_text='Optional device identifier. Useful for detecting patterns, abuse, or GPS accuracy issues.', null=True)),
                ('contribution_type', models.CharField(choices=[('stop_name', 'Stop Name Correction'), ('stop_exists', 'Stop Existence Confirmation'), ('stop_not_exists', 'Stop Non-Existence Report'), ('stop_location', 'Stop Location Refinement'), ('route_exists', 'Route Existence Claim'), ('route_traversal', 'Route Traversal (GPS Trace)'), ('stop_sequence', 'Stop Sequence Confirmation'), ('service_time', 'Service Time Observation')], db_index=True, help_text='Type of observation submitted.', max_length=50)),
                ('subject_ref', models.JSONField(help_text='Opaque reference to what this contribution is about. May contain: - Canonical entity ID (if updating existing) - Geographic hint (lat/lon) - Name or description Structure varies by contribution_type.')),
                ('payload', models.JSONField(help_text="Raw evidence data submitted by the user. Structure varies by contribution_type. Examples: - Stop name: {'name': 'Main Street Station'} - GPS trace: {'points': [{'lat': ..., 'lon': ..., 'timestamp': ...}]} - Service time: {'time': '18:40', 'direction': 'inbound'} This is NOT validated at submission - evaluation happens later.")),
                ('observed_at', models.DateTimeField(db_index=True, help_text='When the user observed this (client-reported timestamp). May be in the past if submitted offline. Used for temporal reasoning about transit service.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the server received this contribution (server time).')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Metadata about how this observation was made. Examples: - gps_accuracy: float (meters) - app_version: string - was_offline: boolean - network_type: string - battery_level: int Used to assess confidence and reliability.')),
                ('contributor', models.ForeignKey(help_text='User who submitted this observation.', on_delete=django.db.models.deletion.PROTECT, related_name='contribution_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution Event',
                'verbose_name_plural': 'Contribution Events',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['contribution_type', 'submitted_at'], name='core_contri_contrib_aa4b8c_idx'), models.Index(fields=['contributor', 'submitted_at'], name='core_contri_contrib_53bfac_idx'), models.Index(fields=['device_id', 'submitted_at'], name='core_contri_device__9bd139_idx'), models.Index(fields=['observed_at', 'contribution_type'], name='core_contri_observe_df595b_idx')],
            },
        ),
    ]
